E-MarketingLearn/Controllers/UserController.cs
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using E_MarketingLearn.Models;
using System.IO;
using System.Diagnostics;
namespace E_MarketingLearn.Controllers
{
    public class UserController : Controller
    {

        public class PaginationModel<T>
        {
            public List<T> Data { get; set; }
            public int TotalCount { get; set; }
            public int PageSize { get; set; }
            public int CurrentPage { get; set; }
            public int TotalPages { get; set; }
        }
        public ActionResult ChangePassword()
        {
            return View();
        }
        [HttpGet]
        public ActionResult EditProfile()
        {
            using (var DB = new dbmarketingModel())
            {
                var IdUserLogin = Convert.ToInt32(Session["UserID"]);
                var userData = DB.tbl_user.Find(IdUserLogin);

                return View(userData);

            
            }
        }

        [HttpPost]
        public ActionResult EditProfile(tbl_user inputUser)
        {
            var IdUserLogin = Convert.ToInt32(Session["UserID"]);
            using (var DB = new dbmarketingModel())
            {
                var Update_Data = DB.tbl_user.Find(IdUserLogin);

                if (Update_Data != null)
                {
                    //Input data
                    Update_Data.u_contact = inputUser.u_contact;
                    Update_Data.u_email = inputUser.u_email;
                    Update_Data.u_name = inputUser.u_name;
                   
                    //Update Data
                    DB.SaveChanges();
                    Session["UserName"] = inputUser.u_name;

                    //Direct Page
                    return RedirectToAction("Index");
                }
            }

            return View(inputUser);
        }




        public ActionResult Details(int id)
        {
            using (var db = new dbmarketingModel())
            {
                var ad = db.tbl_product
                    .Where(p => p.pro_id == id)
                    .Select(p => new ViewModels
                    {

                        pro_id = p.pro_id,
                        pro_fk_user = p.tbl_user.u_id,

                        pro_name = p.pro_name,
                        pro_image = p.pro_image,
                        pro_price = p.pro_price,
                        pro_des = p.pro_des,
                        cat_name = p.tbl_category.cat_name,
                        u_name = p.tbl_user.u_name,
                        u_image = p.tbl_user.u_image,
                        u_contact = p.tbl_user.u_contact,

                        cat_id = p.tbl_category.cat_id

                    })
                    .SingleOrDefault();

                if (ad == null)
                {
                    return HttpNotFound();
                }

                return View(ad);
            }
        }


        // GET: /User/
        public ActionResult Product(int id = 0, int page = 1)
        {



            using (var dbContext = new dbmarketingModel())
            {
                int pageSize = 6; // Jumlah data per halaman

                //List<tbl_product> products = dbContext.tbl_product
                //    .OrderByDescending(p => p.pro_fk_cat)
                //    .Skip((page - 1) * pageSize)
                //    .Take(pageSize)
                //    .ToList();

                var products = dbContext.tbl_product
                .Where(p => p.pro_fk_cat == id)
                .OrderByDescending(p => p.pro_id) //urutkan data berdasar yang terakhir (ID terbesar)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();



                int totalCount = dbContext.tbl_product.Count(p => p.pro_fk_cat == id); // Menghitung jumlah total data berdasarkan ID
                int totalPages = (int)Math.Ceiling((double)totalCount / pageSize);

                var model = new PaginationModel<tbl_product>
                {
                    Data = products,
                    TotalCount = totalCount,
                    PageSize = pageSize,
                    CurrentPage = page,
                    TotalPages = totalPages
                };


                if (products.Count != 0)
                {
                    //Cari data berdasarkan ID dan Item
                    var item = dbContext.tbl_category.Find(id);
                    ViewBag.Category = item.cat_name;

                }
                else
                {
                    ViewBag.NoData = "No data is displayed!";
                }


                return View(model);

            }
        }
        [HttpGet]
        public ActionResult SearchProduct(string search, int page = 1)
        {
            using (var dbContext = new dbmarketingModel())
            {
                int pageSize = 6; // Jumlah data per halaman

                var query = dbContext.tbl_product.AsQueryable();

                if (!string.IsNullOrEmpty(search))
                {
                    query = query.Where(p => p.pro_name.Contains(search));
                }



                var products = query.OrderByDescending(p => p.pro_id)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize)
                    .ToList();

                int totalCount = query.Count();
                int totalPages = (int)Math.Ceiling((double)totalCount / pageSize);

                if (totalCount == 0)
                {
                    @ViewBag.SearchKosong = "Pencarian tidak ditemukan, data kosong";
                }
                var model = new PaginationModel<tbl_product>
                {
                    Data = products,
                    TotalCount = totalCount,
                    PageSize = pageSize,
                    CurrentPage = page,
                    TotalPages = totalPages
                };

                ViewBag.Search = search;
                ViewBag.Result = query.Count();
                return View("Product", model);
            }
        }

        public ActionResult Index(int page = 1)
        {

            if (Session["UserName"] == null)
            {
                return RedirectToAction("Login");
            }

            using (var dbContext = new dbmarketingModel())
            {
                int pageSize = 6; // Jumlah data per halaman

                List<tbl_category> products = dbContext.tbl_category
                    .OrderByDescending(p => p.cat_id)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize)
                    .ToList();

                int totalCount = dbContext.tbl_category.Count();

                int totalPages = (int)Math.Ceiling((double)totalCount / pageSize);

                PaginationModel<tbl_category> model = new PaginationModel<tbl_category>
                {
                    Data = products,
                    TotalCount = totalCount,
                    PageSize = pageSize,
                    CurrentPage = page,
                    TotalPages = totalPages
                };


                if (products.Count == 0)
                {
                    ViewBag.NoData = "No data is displayed!";
                };

                return View(model);

            }

        }
        public ActionResult SignUp()
        {
            return View();
        }
        public ActionResult Logout()
        {
            Session.Clear();
            Session.Abandon();

            return RedirectToAction("Login");
        }
        //GET
        public ActionResult Login()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(tbl_user checkUser)
        {
            if (ModelState.IsValid)
            {
                using (dbmarketingModel db = new dbmarketingModel())
                {
                    // Login Admin

                    var obj = db.tbl_user.Where(a => a.u_email.Equals(checkUser.u_email) && a.u_password.Equals(checkUser.u_password)).FirstOrDefault();

                    if (obj != null)
                    {
                        //// Simpan identifier unik pengguna dalam cookie
                        //// Di sini kita menggunakan ID pengguna sebagai identifier unik
                        //System.Web.Security.FormsAuthentication.SetAuthCookie(obj.u_email.ToString(), remember);

                        Session["UserID"] = obj.u_id.ToString();
                        Session["UserName"] = obj.u_name.ToString();
                        Session["imgpath"] = obj.u_image;

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["message"] = "Invalid Username and Password";
                        return View("Login");
                    }
                }
            }
            return View(checkUser);
        }

        //Validasi Gambar
        private bool IsImage(HttpPostedFileBase myfile)
        {
            // Daftar tipe file gambar yang diperbolehkan
            string[] allowedExtensions = { ".jpg", ".jpeg", ".png" };

            // Mendapatkan ekstensi file
            string fileExtension = Path.GetExtension(myfile.FileName);


            // Memeriksa apakah ekstensi file ada dalam daftar yang diperbolehkan
            return allowedExtensions.Contains(fileExtension.ToLower());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(tbl_user modelsUser, HttpPostedFileBase file)
        {

            if (file != null && file.ContentLength > 0)



                try
                {
                    if (Msg.ValidasiUpload.ValidasiPhp(file.FileName))
                    {

E-MarketingLearn/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
        <link href="~/Content/Css/BoostrapCss/bootstrap.min.css" rel="stylesheet" />
      <!-- Daftar file CSS dan JS yang diperlukan -->
    @RenderSection("style", required:false)
    <title>@ViewBag.Title</title>
 
</head>
<body>
     <!-- Header, menu navigasi, atau elemen lainnya -->
    @RenderSection("Header", required: false)


    @RenderBody()
   


      <!-- Footer atau elemen lainnya -->
    @RenderSection("Footer", required: false)

   <!-- Daftar file JavaScript yang diperlukan -->
    @RenderSection("Scripts", required: false)
 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

E-MarketingLearn/Views/Shared/_LayoutNav.cshtml
@{
    if (Session["UserName"] == null)
    {
        Response.Redirect("~/user/login");
    }
    
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Css/BoostrapCss/bootstrap.min.css" rel="stylesheet" />
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
        }

        .container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            margin-top: 20px;
        }

        .product {
            width: 300px;
            margin-bottom: 20px;
            padding: 20px;
            border: 1px solid #ccc;
            text-align: center;
        }

        .product img {
            max-width: 100%;
            height: auto;
        }

        .product h3 {
            margin-top: 10px;
        }

        .product p {
            color: #888;
        }

        .product button {
            margin-top: 10px;
            background-color: #333;
            color: #fff;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
        }

        .product button:hover {
            background-color: #555;
        }

        /*Pagination*/
        .pagination {
            display: flex;
            justify-content: center;
            margin-top: 20px;
        }

        .pagination a,
        .pagination span {
            display: inline-block;
            padding: 8px 16px;
            text-decoration: none;
            color: #000;
            border: 1px solid #ddd;
        }

        .pagination a:hover {
            background-color: #ddd;
        }

        .pagination .active {
            background-color: #4CAF50;
            color: white;
            border: 1px solid #4CAF50;
        }


    </style>
    @RenderSection("style", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "User")">Market</a>
        

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "user")">Home</a>
                    </li>

                    <li>
                        <a class="nav-link" href="@Url.Action("mypost", "user")">My Post</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="accountDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="@Url.Content(Session["imgpath"].ToString())" style="width:30px;height:30px;" />
                            Welcome, <b>@Session["UserName"].ToString().ToUpper()</b>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="accountDropdown">
                             <a class="dropdown-item" href="@Url.Action("editprofile", "user")">Edit Profile</a>
                             <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Upload", "user")">Upload Product</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("logout", "user")">Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br />

    @RenderSection("Header", required: false)
    @RenderBody()
    @RenderSection("Footer", required: false)
    @RenderSection("Scripts", required: false)
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

E-MarketingLearn/Views/Shared/_LayoutNavAdmin.cshtml
@{
    if (Session["UserName"] == null)
    {
        Response.Redirect("~/admin/login");
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Css/BoostrapCss/bootstrap.min.css" rel="stylesheet" />
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
        }

        .container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            margin-top: 20px;
        }

        .product {
            width: 300px;
            margin-bottom: 20px;
            padding: 20px;
            border: 1px solid #ccc;
            text-align: center;
        }

        .product img {
            max-width: 100%;
            height: auto;
        }

        .product h3 {
            margin-top: 10px;
        }

        .product p {
            color: #888;
        }

        .product button {
            margin-top: 10px;
            background-color: #333;
            color: #fff;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
        }

        .product button:hover {
            background-color: #555;
        }

        /* Pagination */
        .pagination {
            display: flex;
            justify-content: center;
            margin-top: 20px;
        }

        .pagination a,
        .pagination span {
            display: inline-block;
            padding: 8px 16px;
            text-decoration: none;
            color: #000;
            border: 1px solid #ddd;
        }

        .pagination a:hover {
            background-color: #ddd;
        }

        .pagination .active {
            background-color: #4CAF50;
            color: white;
            border: 1px solid #4CAF50;
        }

        /* New Navigation Styles */
        .navbar {
            background-color: #E57373; /* Warna latar belakang */
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .navbar-brand {
            color: #fff;
            font-size: 24px;
        }

        .navbar-toggler-icon {
            background-color: #fff;
        }

        .navbar-nav .nav-item .nav-link {
            color: #fff;
        }

        .navbar-nav .nav-item .nav-link:hover {
            color: #F48FB1; /* Warna teks saat dihover */
        }

    </style>
    @RenderSection("style", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <a class="navbar-brand" href="#">Market</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","admin")">Home</a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("dashboard", "admin")">Dashboard</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br />
     
    @RenderSection("Header", required: false)
    @RenderBody()
    @RenderSection("Footer", required: false)
    @RenderSection("Scripts", required: false)
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>